name: CI
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q --ignore 113 631 211 212 112 311

      - name: Generate recent changes
        uses: kemayo/actions-recent-changelog@v1
        with:
          input: CHANGELOG.md
          output: RECENT_CHANGES.md

      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -d
